### ISSUE TITLE
Possibly redundant variable + Question on scaling

### ISSUE THREAD

**Issue by ghost** [mmukhopadhyay/-Efficient-Manifold-Learning-Using-Spherelets#2]
Hi, 

I am trying to implement this algorithm in python. I have a question related to the following line

https://github.com/mmukhopadhyay/-Efficient-Manifold-Learning-Using-Spherelets/blob/93a1844b32755bb3984a635bc682ef860fa726de/SPCA_functions.R#L42

In this line, you compute `centeredX` which is not used in any of the following functions. Should it be discarded?

### Pure question
Furthermore, I noticed that the function `prcomp` only centers the data (i.e. no scaling). What is the reason to do just centering and no scaling?

**Comment by mmukhopadhyay** [comment]
Yes, you may drop that.

PRCOMP finds the eigenvalues and corresponding eigenvectors of  the variance covariance matrix. If Z is the centered matrix corresponding to X, then ZZ^t/n gives the variance covariance matrix corresponding to X. There is no need for column-wise scaling. I think, this is why PRCOMP only centers the data.

**Comment by ghost** [comment]
Thank you very much for your quick answer!
